name: Walk and Publish 

on:
  schedule:
    - cron:  '0 */3 * * *' # every three hour
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          muser: ${{ secrets.muser }}
          mpass: ${{ secrets.mpass }}
          murl: ${{ secrets.murl }}
          bot_token: ${{ secrets.bot_token }}
          channel_id: ${{ secrets.channel_id }}
          chat_id: ${{ secrets.chat_id }}
          footer: ${{ secrets.footer }}
        run: |
          #python rss.py
          python bot.py
